---
title: "Introduction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Introduction**

The `recodeflow` package is the package you need to transform variables from multiple data sets into consistent (harmonized) variables.

`recodeflow` has the basic functions and templates required to define, transform, and harmonize variables for any dataset.


**Why should I use `recodeflow`?**

Let's walk through a hypothetical example to explain purpose of the `recodeflow` package. 

Each year, Canadians complete a survey and the data is collected. The data is then coded so scientists can use the data for research. You, a scientist, want to combine the survey results over the last 10 years to answer two research questions, **but there's a catch:**

At the survey level: 

- Not every survey question was asked each year.
- The survey answers changed from year to year. 

At the data level:

- Questions are not coded the same from year to year (e.g., variable names differ)
- Answers are not coded the same from year to year (e.g., height is coded in meters in some years and in feet other years)

The data is messy! You start the painstaking and timely process of cleaning and transforming each variable. You think "there must be a better way".

That's were `recodeflow` comes to the rescue. 

With `recodeflow` you can clean and transform your entire dataset with a few lines of code. Even better, once you've defined your variables, you have a variable reference that you can reuse or share with colleagues - saving you even more time down the line.

.........

**How does `recodeflow` work?**

Using templates `variable_sheet` and `variable_details` you list your variables, and state how to transform the each variable. 

Once your variables are defined, you use `recodeflow` functions to clean and sort your data. The main `recodeflow` function is `rec_with_table` which transforms variables within you dataset(s) based on how you've defined the variable in `variable_sheet` and `variable_details`.


**What's included in `recodeflow` package?**

The `recodeflow` package includes: 

- **functions** require to clean, sort, and transform variables.
- **templates:**

  - **`variable_sheet`** a list of variables in a dataset that can be transformed, and
  - **`variable_details`** a list of instructions on how to transform variables.


We've also created the following documentation, to help you understand `recodeflow`:

- **how to guides** examples of how to use `recodeflow` and adapt `recodeflow` for your dataset
- **articles** that describe package elements (e.g., variable_sheet) in detail 
- **references** that describe all functions used in `recodeflow`
- **example data** to demonstrate `recodeflow` functions and templates.


**Examples where `recodeflow` is used**

Currently `recodeflow` is used in packages that harmonize health surveys and health administrative databases. 

- `cchsflow` is a package that harmonizes variables across cycles of the Canadian Community Health Survey (CCHS). cchsflow is (published)[https://big-life-lab.github.io/cchsflow/index.html].

-`raiflow` is a package that will harmonize variables within the Resident Assessments Instruments (RAI) from various sources: Canada's Continuing Care Reporting System (CCRS), and Ontario's Resident Assessment Instrutment for Home Care (RAI-HC). `raiflow` is currently underdevelopment. 










