name: Bug Report
description: File a bug report.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Use the following input ...
        2. Run the following command ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        A clear and concise description of what you expected to happen.
  - type: textarea
    id: system
    attributes:
      label: System Info
      placeholder: |
        - OS:
        - R Version:
        - recodeflow version/commit:
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        Screenshots can also be attached.
